# Generated by Django 3.0.5 on 2020-05-26 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_auto_20200506_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=30)),
                ('forma_platnosci', models.CharField(choices=[('przelew', 'przelew'), ('gotowka', 'gotówka')], max_length=75)),
                ('data_badania', models.DateField()),
                ('data_wystawienia_faktury', models.DateTimeField(default=django.utils.timezone.now)),
                ('rabat', models.IntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('usluga', models.ManyToManyField(to='invoices.Service')),
            ],
        ),
    ]
