# Generated by Django 3.0.5 on 2020-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_wartosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cena',
            field=models.FloatField(),
        ),
    ]
