# Generated by Django 3.0.5 on 2020-06-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20200606_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Service')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicesQuantity',
        ),
        migrations.AddField(
            model_name='invoice',
            name='uslugi',
            field=models.ManyToManyField(to='invoices.ServiceItem'),
        ),
    ]
