# Generated by Django 3.0.5 on 2020-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20200606_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uslugi',
            field=models.ManyToManyField(blank=True, null=True, to='invoices.ServiceItem'),
        ),
    ]
