# Generated by Django 3.0.5 on 2020-06-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20200606_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='uslugi',
        ),
    ]
