# Generated by Django 3.0.5 on 2020-06-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_remove_invoice_uslugi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='usluga',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='faktura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
