# Generated by Django 3.0.5 on 2020-06-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20200607_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='usluga',
            field=models.ManyToManyField(to='invoices.Service', verbose_name='usługi'),
        ),
    ]
