# Generated by Django 3.0.5 on 2020-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20200609_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceitem',
            old_name='usluga_fk',
            new_name='usluga',
        ),
        migrations.AddField(
            model_name='invoice',
            name='usluga',
            field=models.ManyToManyField(to='invoices.Service', verbose_name='usługi'),
        ),
    ]
