# Generated by Django 3.0.5 on 2020-06-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20200609_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='usluga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Service'),
        ),
    ]
