# Generated by Django 3.0.5 on 2020-06-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_auto_20200609_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='usluga',
            new_name='uslugi',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='faktura',
        ),
    ]
