# Generated by Django 3.0.5 on 2020-06-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_auto_20200609_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='usluga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Service'),
        ),
    ]
