# Generated by Django 3.0.5 on 2020-06-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_auto_20200609_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='faktura',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
            preserve_default=False,
        ),
    ]
