# Generated by Django 3.0.5 on 2020-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_serviceitem_faktura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uslugi',
            field=models.ManyToManyField(blank=True, null=True, to='invoices.ServiceItem'),
        ),
    ]
