# Generated by Django 3.0.5 on 2020-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_auto_20200721_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='rabat',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='rabat',
            field=models.IntegerField(blank=True, null=True, verbose_name='rabat [%]'),
        ),
    ]
