# Generated by Django 3.0.5 on 2020-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_auto_20200721_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='rabat',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='rabat [%]'),
        ),
    ]
