# Generated by Django 3.1.3 on 2021-02-21 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_auto_20200721_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='termin_platnosci',
            field=models.DateField(choices=[('7 dni', 7), ('14 dni', 14), ('21 dni', 21)], default=django.utils.timezone.now, verbose_name='termin płatności'),
            preserve_default=False,
        ),
    ]
