# Generated by Django 3.1.3 on 2021-02-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200528_1133'),
        ('clients', '0006_auto_20200527_0914'),
        ('invoices', '0029_auto_20210221_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='osoba_prywatna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='termin_platnosci',
            field=models.IntegerField(blank=True, choices=[(0, 'dzisiaj'), (7, '7 dni'), (14, '14 dni'), (21, '21 dni')], default=0, null=True, verbose_name='termin płatności'),
        ),
    ]
