# Generated by Django 3.1.3 on 2021-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_auto_20210221_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='komentarz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
