# Generated by Django 3.1.3 on 2021-03-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_invoice_komentarz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='komentarz',
        ),
        migrations.AddField(
            model_name='invoice',
            name='komentarz1',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='komentarz2',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
