# Generated by Django 3.1.3 on 2021-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_auto_20210304_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='komentarz3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='komentarz 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='komentarz1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='komentarz 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='komentarz2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='komentarz 2'),
        ),
    ]
