# Generated by Django 3.0.6 on 2020-05-04 12:26

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=50)),
                ('NIP', models.CharField(max_length=50)),
                ('REGON', models.CharField(max_length=50)),
                ('pliki_firmy', models.FileField(upload_to=companies.models.get_upload_folder_name)),
            ],
        ),
    ]
