# Generated by Django 3.0.5 on 2020-05-05 13:28

import companies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='NIP',
        ),
        migrations.RemoveField(
            model_name='company',
            name='REGON',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pliki_firmy',
        ),
        migrations.AddField(
            model_name='company',
            name='nip',
            field=models.CharField(default=None, max_length=50, verbose_name='NIP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='regon',
            field=models.CharField(default=None, max_length=50, verbose_name='REGON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='nazwa',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(blank=True, upload_to=companies.models.get_upload_folder_name, verbose_name='Pliki')),
                ('data_dodania', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
