# Generated by Django 3.0.5 on 2020-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200506_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nazwa',
            field=models.CharField(max_length=69, verbose_name='Nazwa'),
        ),
    ]
