# Generated by Django 3.0.5 on 2020-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='temat',
            field=models.CharField(default='Brak tematu', max_length=50),
        ),
    ]
