# Generated by Django 3.0.5 on 2020-04-24 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_message_temat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data_odczytania',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='wiadomosc',
            field=models.TextField(verbose_name='wiadomość'),
        ),
    ]
