# Generated by Django 3.0.5 on 2020-04-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_auto_20200424_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data_odczytania',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_odpowiedzi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
