# Generated by Django 3.0.5 on 2020-04-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20200424_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data_odczytania',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_odpowiedzi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_utworzenia',
            field=models.DateTimeField(),
        ),
    ]
