# Generated by Django 3.0.6 on 2020-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0006_auto_20200424_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='temat',
            field=models.CharField(max_length=50),
        ),
    ]
