# Generated by Django 3.0.5 on 2020-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('numer_telefonu', models.CharField(max_length=20, verbose_name='numer telefonu')),
                ('email', models.CharField(max_length=50, verbose_name='adres e-mail')),
                ('nr_rejestr', models.CharField(max_length=20, verbose_name='numer w rejestrze')),
                ('data_badania', models.DateField(auto_now=True, verbose_name='data badania')),
                ('data_waznosci_badania', models.DateField(verbose_name='data upływu badania')),
                ('podstawa_prawna', models.CharField(choices=[('kier_zaw', 'kierowca zawodowy'), ('kier_uprz', 'kierowca uprzywilejowany'), ('instr_egz', 'instruktor / egzaminator'), ('zatrz_pra_jaz', 'zatrzymane prawo jazdy'), ('inna', 'inna')], max_length=50, verbose_name='podstawa prawna')),
                ('komentarz', models.TextField(blank=True, verbose_name='komentarz')),
                ('badany_60', models.BooleanField(default=False, verbose_name='badany ukończył 60 rok życia')),
            ],
        ),
    ]
