# Generated by Django 3.0.5 on 2020-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_waznosci_badania',
            field=models.DateField(auto_now=True, verbose_name='data upływu badania'),
        ),
    ]
