# Generated by Django 3.0.5 on 2020-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200421_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_badania',
            field=models.DateField(verbose_name='data badania'),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_waznosci_badania',
            field=models.DateField(verbose_name='data upływu badania'),
        ),
    ]
