# Generated by Django 3.0.6 on 2020-05-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clients', '0004_remove_client_badany_60'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pracodawca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
    ]
