# Generated by Django 3.0.5 on 2020-05-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200506_0847'),
        ('clients', '0005_client_pracodawca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pracodawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
