# Generated by Django 3.1.3 on 2021-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200527_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_badania',
            field=models.DateField(blank=True, null=True, verbose_name='data badania'),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_waznosci_badania',
            field=models.DateField(blank=True, null=True, verbose_name='data upływu badania'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='adres e-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nr_rejestr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numer w rejestrze'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numer telefonu'),
        ),
        migrations.AlterField(
            model_name='client',
            name='podstawa_prawna',
            field=models.CharField(blank=True, choices=[('kier_zaw', 'kierowca zawodowy'), ('kier_uprz', 'kierowca uprzywilejowany'), ('instr_egz', 'instruktor / egzaminator'), ('zatrz_pra_jaz', 'zatrzymane prawo jazdy'), ('inna', 'inna')], max_length=50, null=True, verbose_name='podstawa prawna'),
        ),
    ]
